name: Deployment

on:
  pull_request:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display Private Key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /home/restaurant@smartduuka/public_html
            git pull origin dev
            git fetch origin
            git reset --hard origin/dev
            composer update
            php artisan migrate --force
            npm update
            npm run production
